first<-read.table("household_power_consumption.txt",header=TRUE,sep=";",nrows=1,quote="",na.strings="?")
cNames<-colnames(first)
t1<-paste(first$Date," ",first$Time)
t2<- strptime(t1,format="%d/%m/%Y %H:%M:%S")
start<-strptime("01/02/2007 0:1:0",format="%d/%m/%Y %H:%M:%S")
dif<-difftime(start,t2,units="mins")
dat<-read.table("household_power_consumption.txt",col.names=cNames,sep=";",nrows=2880,quote="",na.strings="?", skip=dif)
dat$Date<-paste(dat$Date,dat$Time)
dat$Date<-strptime(dat$Date,"%d/%m/%Y %H:%M:%S")
dat<-subset(dat,select=-Time)
par(mfrow=c(2,2),mar=c(4,4,3,2),oma=c(0,0,0,0))
with(dat,{
  plot(Date,Global_active_power,type="n",main="",xlab="",ylab="Global Active Power",cex.lab=0.8,cex.axis=0.8)
  lines(Date, Global_active_power)
  plot(Date,Voltage,type="n",main="",xlab="datetime",ylab="Voltage",cex.lab=0.8,cex.axis=0.75)
  lines(Date, Voltage)
  plot(Date,Sub_metering_1,type="n",main="",xlab="",ylab="Energy sub metering",cex.lab=0.8,cex.axis=0.75)
  lines(Date,Sub_metering_1,col="black")
lines(Date,Sub_metering_2,col="red")
lines(Date,Sub_metering_3,col="blue")
legend("topright",lty=1,bty="n", cex=0.8,text.width=85000,col = c("black","red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
  plot(Date,Global_reactive_power,type="n",main="",xlab="datetime",ylab="Global_reactive_power",cex.lab=0.8,cex.axis=0.75)
lines(Date,Global_reactive_power)
})

dev.copy(png,file="plot4.png",width=480,height=480)
dev.off()