first<-read.table("household_power_consumption.txt",header=TRUE,sep=";",nrows=1,quote="",na.strings="?")
cNames<-colnames(first)
t1<-paste(first$Date," ",first$Time)
t2<- strptime(t1,format="%d/%m/%Y %H:%M:%S")
start<-strptime("01/02/2007 0:1:0",format="%d/%m/%Y %H:%M:%S")
dif<-difftime(start,t2,units="mins")
dat<-read.table("household_power_consumption.txt",col.names=cNames,sep=";",nrows=2880,quote="",na.strings="?", skip=dif)
dat2<-data.frame("time"=paste(dat$Date,dat$Time),"power"=dat$Global_active_power)
dat2$time<-strptime(dat2$time,"%d/%m/%Y %H:%M:%S")
with(dat2,plot(time, power ,  type='n',main="",xlab="",ylab="Global Active Power (kilowatts)",,cex.lab=0.8,cex.axis=0.75))
with(dat2,lines(time,power))
dev.copy(png,file="plot2.png")
dev.off()