first<-read.table("household_power_consumption.txt",header=TRUE,sep=";",nrows=1,quote="",na.strings="?")
cNames<-colnames(first)
t1<-paste(first$Date," ",first$Time)
t2<- strptime(t1,format="%d/%m/%Y %H:%M:%S")
start<-strptime("01/02/2007 0:1:0",format="%d/%m/%Y %H:%M:%S")
dif<-difftime(start,t2,units="mins")
dat<-read.table("household_power_consumption.txt",col.names=cNames,sep=";",nrows=2880,quote="",na.strings="?", skip=dif)
dat$Date<-paste(dat$Date,dat$Time)
dat$Date<-strptime(dat$Date,"%d/%m/%Y %H:%M:%S")
dat<-subset(dat,select=-Time)
with(dat,plot(Date, Sub_metering_1 ,type="n",main="",xlab="",ylab="Energy sub metering",cex.lab=0.8,cex.axis=0.75))
with(dat,lines(Date,Sub_metering_1,col="black"))
with(dat,lines(Date,Sub_metering_2,col="red"))
with(dat,lines(Date,Sub_metering_3,col="blue"))
legend("topright",   lty=1,bty='o', cex=0.6,text.width=45000,col = c("black","red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot3.png",width=480,height=480)
dev.off()